name: Netlify Storybook Production Environment

on:
  release:
    types:
      - released

jobs:
  publishOnMasterRelease:
    name: Deploying on Netlify Storybook Production Environment
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'released'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        run: npm ci
        working-directory: ./
      - name: Build storybook
        run: npm run build:storybook
        working-directory: ./
      - name: Install Netlify
        run: npm i netlify-cli --no-save
      - name: Deploying on Netlify Storybook Production Environment
        run: netlify deploy --prod --dir=./docs/storybook --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --site=${{ secrets.NETLIFY_STORYBOOK_ID }}
